"""init_table

Revision ID: 4f9ef159bb49
Revises: 
Create Date: 2024-07-12 11:35:14.978528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9ef159bb49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_pk_table',
    sa.Column('pk', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_text_pk_table_pk'), 'text_pk_table', ['pk'], unique=False)
    op.create_table('uuid_pk_table',
    sa.Column('pk', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_uuid_pk_table_pk'), 'uuid_pk_table', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uuid_pk_table_pk'), table_name='uuid_pk_table')
    op.drop_table('uuid_pk_table')
    op.drop_index(op.f('ix_text_pk_table_pk'), table_name='text_pk_table')
    op.drop_table('text_pk_table')
    # ### end Alembic commands ###
